name: Jekyll Site CI
on:
  push:
    branches: [ main ] # 这里其实可以填写多个监听的分支，也可以不使用这个参数，监听所有push操作。
                        # 因为我需要自动构建的分支是build分支，所以这里填写build分支。
  pull_request:         # 这个可以不要。
    branches: [ main ] # 同on.push.branches。

jobs:
  build:
    runs-on: ubuntu-latest # GitHub Action可以在Linux、MacOS、Windows环境下构建项目。这里使用的Linux环境。
    steps:
    - uses: actions/checkout@v3

    # Use GitHub Actions' cache to shorten build times and decrease load on servers
    - uses: actions/cache@v3
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    # https://github.com/marketplace/actions/jekyll-actions
    - uses: helaili/jekyll-action@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        target_branch: 'gh-pages'
